export const quotes = [
  "Keep typing until it compiles! 💪",
  "You’re not debugging, you’re refining greatness. 🚀",
  "Commit small, commit often. 🧠",
  "Even the best devs break production once in a while 😅",
  "Your coffee believes in you ☕",
  "Code. Break. Fix. Repeat. 🔁",
  "You’re just one semicolon away from success ;)",
  "Keep typing until it compiles! 💪",
  "You’re not debugging, you’re refining greatness. 🚀",
  "Commit small, commit often. 🧠",
  "Even the best devs break production once in a while 😅",
  "Your coffee believes in you ☕",
  "Code. Break. Fix. Repeat. 🔁",
  "You’re just one semicolon away from success ;)",
  "Push today, brag tomorrow. 📦",
  "Somewhere, your code is running just fine… probably. 🤞",
  "Refactor like nobody’s watching. ✨",
  "Don’t panic, it’s just a missing bracket. 😎",
  "Console.log(‘Confidence!’); 🖥️",
  "Sometimes you need to restart — not just your computer. 🔄",
  "Bug today, legend tomorrow. 🐞➡️🏆",
  "Tabs or spaces? The eternal battle continues. ⚔️",
  "Keep calm and npm install. 🧘",
  "You are the compiler of your destiny. 🧩",
  "Merge conflicts build character. 💥",
  "If it works, don’t touch it. 🙈",
  "Your code is valid. Your feelings are too. ❤️",
  "Debugging: because we love pain in small doses. 😅",
  "A clean codebase is a happy codebase. 🧼",
  "Don’t let one bug ruin your day. 🐛",
  "Eat. Sleep. Code. Repeat. 💻",
  "The real MVP is version control. 🧠",
  "Your repo called. It misses your commits. 🥹",
  "You can’t spell ‘success’ without ‘CSS’. 🎨",
  "You’re not late — you’re on dev time. 🕓",
  "One more push before the weekend! 🚢",
  "Stay hydrated and hydrated your code. 💧",
  "Behind every bug is a lesson. 📖",
  "Ship it like you mean it. 🚀",
  "404: Motivation not found — just kidding, you got this! 💥",
  "Sleep is for the weak (and well-rested). 😴",
  "You’re writing history with every commit. 📝",
  "Keep your functions pure and your thoughts clearer. 🧠",
  "The world needs your next project. 🌍",
  "Good code speaks for itself — but comments help. 🗣️",
  "Behind every smooth UI is a frustrated dev. 🎨🔥",
  "Error logs are love letters from your code. 💌",
  "Don’t let your dreams be commented out. 💭",
  "Your bug fixes are acts of heroism. 🦸",
  "One day, this will make sense. 🌀",
  "There’s beauty in the syntax. 💫",
  "Refactor fearlessly. 🔧",
  "Sometimes the best feature is the one you didn’t write. ⚡",
  "You’re doing great, even if Git disagrees. 💔",
  "Coding is 90% staring at the screen, 10% magic. 🪄",
  "Nothing feels better than a green test suite. ✅",
  "May your commits be clean and your code reviews kind. 💬",
  "You deserve a break — not another dependency. ☕",
  "The best debugger is persistence. 🧩",
  "Your code is art, your console is your canvas. 🎨",
  "Trust the process, even if npm doesn’t. 📦",
  "You’re just one commit away from greatness. 🌟",
  "Behind every merge is a miracle. 🧠",
  "Remember to breathe — even if your code doesn’t. 🌬️",
  "Happy dev, happy app. 😄",
  "Git push, but don’t push yourself too hard. ❤️",
  "Believe in your algorithm. 💫",
  "One PR at a time. 🧱",
  "Coding is just digital gardening. 🌱",
  "Your logic is flawless — mostly. 🤓",
  "You are the framework of your future. 🏗️",
  "Great things take time — and a few stack overflows. ⏳",
  "Sleep on the bug, fix it tomorrow. 💤",
  "Good code is like humor — it needs no explanation. 😂",
  "Documentation is self-care. 📚",
  "Don’t forget to commit your joy. 😊",
  "Your brain is the best IDE. 🧠",
  "Push, pray, and deploy. 🙏",
  "Sometimes the best code is no code. 🫢",
  "You can’t ‘undo’ burnout — take breaks. 🌤️",
  "Caffeine is the unofficial dependency. ☕",
  "You’re compiling greatness. 🔥",
  "Every bug fix deserves a celebration. 🎉",
  "Trust your instincts — and your linter. 🧭",
  "Keep building. Keep believing. 🏗️",
  "Behind every great dev is a ton of logs. 📜",
  "You’ve got this — just one more feature. 💪",
  "The code may fail, but you won’t. 🌟",
  "Take pride in your console.logs. 🖥️",
  "Write code like poetry. ✍️",
  "Not all heroes wear capes; some wear headphones. 🎧",
  "Good commits make good memories. 📘",
  "One small commit for you, one giant leap for the project. 🌕",
  "Even bugs have feelings. 🐛",
  "Trust your git history, but not too much. 🧾",
  "Keep learning — the docs are your best friends. 📖",
  "When in doubt, restart. 🔁",
  "Your next commit could change everything. 💫",
  "Perfection is just another pull request away. 🌈",
  "The terminal is your temple. 🕹️",
  "Don’t fear failure — fear not trying. ⚡",
  "Ship something you’re proud of. 🚢",
  "Keep your stack clean and your mindset cleaner. 🧹",
  "A happy dev writes happy code. 😄",
  "Your mood matters — log it and move on. 📝",
  "Keep pushing (both Git and yourself). 💪",
  "In the end, it’s all just 1s and 0s — and passion. ❤️",
  // 💪 Motivational
  "Keep typing until it compiles! 💪",
  "You’re not debugging, you’re refining greatness. 🚀",
  "Commit small, commit often. 🧠",
  "Bug today, legend tomorrow. 🐞➡️🏆",
  "Refactor like nobody’s watching. ✨",
  "You’re compiling greatness. 🔥",
  "One PR at a time. 🧱",
  "Trust the process, even if npm doesn’t. 📦",
  "Good commits make good memories. 📘",
  "The best debugger is persistence. 🧩",
  "You’re just one commit away from greatness. 🌟",
  "Push, pray, and deploy. 🙏",
  "Behind every merge is a miracle. 🧠",
  "Keep your stack clean and your mindset cleaner. 🧹",
  "The code may fail, but you won’t. 🌟",
  "You are the compiler of your destiny. 🧩",
  "A happy dev writes happy code. 😄",
  "Even bugs have feelings. 🐛",
  "Good code speaks for itself — but comments help. 🗣️",
  "Keep calm and npm install. 🧘",

  // 😂 Funny
  "Even the best devs break production once in a while 😅",
  "Your coffee believes in you ☕",
  "Tabs or spaces? The eternal battle continues. ⚔️",
  "Don’t panic, it’s just a missing bracket. 😎",
  "Console.log('Confidence!'); 🖥️",
  "Somewhere, your code is running fine… probably. 🤞",
  "Sleep is for the weak (and well-rested). 😴",
  "Caffeine is the unofficial dependency. ☕",
  "Your bug fixes are acts of heroism. 🦸",
  "There’s beauty in the syntax. 💫",
  "Not all heroes wear capes; some wear headphones. 🎧",
  "You can’t spell ‘success’ without ‘CSS’. 🎨",
  "One small commit for you, one giant leap for the repo. 🌕",
  "Your repo called. It misses your commits. 🥹",
  "Behind every smooth UI is a frustrated dev. 🎨🔥",
  "When in doubt, restart. 🔁",
  "If it works, don’t touch it. 🙈",
  "Error logs are love letters from your code. 💌",
  "You’re not late — you’re on dev time. 🕓",
  "Code. Break. Fix. Repeat. 🔁",

  // 🔥 Roast Mode
  "Your code works, but nobody knows why — including you. 😈",
  "You named a variable ‘data’? Revolutionary. 🙄",
  "Wow, another console.log in production. Bold move. 🔥",
  "You write code like you Google — aggressively and with panic. 😂",
  "You call that a function? It’s more like an adventure. 🧭",
  "Bro, your code needs therapy, not debugging. 🧠",
  "I’ve seen spaghetti with better structure than your code. 🍝",
  "You must be a magician — bugs disappear when you call me over. 🎩",
  "Commit message: ‘fix stuff’. Wow, poetic. 📝",
  "You’re the reason the linter cries at night. 😭",
  "Your app runs only on your machine — truly cutting-edge. 🖥️",
  "That commit message aged like milk. 🥛",
  "You have more TODOs than actual features. 🤡",
  "You must love errors — you make so many of them. 💥",
  "You debug with print statements? Brave. 🦁",
  "I didn’t know JavaScript could cry, but your code proved it. 😭",
  "Every time you push to main, a QA angel loses its wings. 😇",
  "You treat production like a playground. 🧸",
  "Your API response time could cook a pizza. 🍕",
  "You code like it’s still Internet Explorer era. 🕰️",
  "Your indentation has trust issues. 📏",
  "That ‘temporary fix’ has been there since 2020. 🕸️",
  "You must be allergic to documentation. 📄",
  "Your Git history looks like a horror story. 👻",
  "Your CSS is held together by pure luck. 🎯",
  "You wrote code so bad, ChatGPT asked for a raise. 💀",
  "The only thing consistent in your code is inconsistency. 🔁",
  "You deploy chaos with confidence. 💣",
  "Your if-else ladder needs a fire escape. 🔥",
  "You commit like you’re defusing a bomb. 💣",
  "Your tests pass only when the stars align. 🌌",
  "Your code runs, but at what cost? 💸",
  "You’re a walking merge conflict. ⚔️",
  "You’ve turned Stack Overflow into Stack Overuse. 📚",
  "Your function names are longer than your attention span. 🧠",
  "That feature works in theory, not reality. 🪄",
  "You’ve unlocked a new error: emotional damage. 💔",
  "Your syntax is crying for help. 😢",
  "You reinvented the wheel — as a triangle. 🔺",
  "If spaghetti code was an Olympic sport, you’d win gold. 🥇",
  "Your variable names are a crime scene. 🚓",
  "Your code comments read like apologies. 😬",
  "You’ve made more bugs than GitHub stars. 🐞⭐",
  "Your logic is so nested it has trust issues. 🕳️",
  "You test in prod? You’re the chosen one. 🔥",
  "You call it AI; I call it random if statements. 🤖",
  "Your indentation strategy is chaos theory. 📐",
  "Your app works only when you’re watching it. 👀",
  "That ‘quick fix’ broke the entire internet. 🌐",
  "You code like you hate your future self. 😭",
  "You’re the human equivalent of a race condition. ⏱️",
  "If Git blame was a sport, you’d be MVP. 🏆",
  "You treat semicolons like optional decorations. 🎉",
  "You and merge conflicts are in a toxic relationship. 💔",
  "You’ve achieved 100% coverage in chaos. ☠️",
  "Your code review comments need therapy. 🧘",
  "Your async functions are just sync ones pretending. 😅",
  "You refactor like a demolition expert. 💣",
  "Your commits scare junior devs. 👶💀",
  "Your project structure looks like a family tree gone wrong. 🌳",
  "You built a microservice that’s more micro than service. 🧬",
  "You’re not debugging — you’re emotionally bonding with errors. 😭"
];
